import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`flex flex-col ${geistSans.variable} ${geistMono.variable} antialiased items-center`}
      >
      <main>
          <img
            src="./Assets/frogger.png"
            alt="Efrogr by Locker"
          />
          {children}
          <p>Controls: W,A,S,D or Arrow Keys</p>
      </main>
      <footer>
        <p className="footer-text">Made with ❤ by Liam Melkersson 2024</p>
      </footer>
        
      </body>
    </html>
  );
}
